version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db  # Para persistir los datos entre reinicios

  backend:
    build: .
    container_name: user-microservice-fastapi
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - mongodb
    volumes:
      - .:/app
    command: uvicorn app.main:app --reload

volumes:
  mongodb-data:
